name: Rubocop

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 3.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rubocop -l